name: First Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: run a sample github action
      run: echo "this workflow run successfully for this github action"

    
